# Generated by Django 4.2.3 on 2023-07-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('pimage', models.FileField(default='anonymous.jpg', upload_to='seller_profile/')),
                ('desc', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.seller_user')),
            ],
        ),
    ]
